import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import Navbar from '@/components/Navbar';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Taxi Booking',
  description: 'Generated by create next app',
  icons: {
    icon: '/icons.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <ClerkProvider>
        <body className={inter.className}>
          <Head>
            <link rel='shortcut icon' href='/taxi.png' />
          </Head>
          <Navbar />
          {children}
        </body>
      </ClerkProvider>
    </html>
  );
}
